/*
 * PINV databse schema generating script
 * Created by: Jarrod Nix
 * Date: 04-09-2017
*/

CREATE TABLE ITEM (
	INo					VARCHAR(9) 					NOT NULL					 PRIMARY KEY, 
	Name					VARCHAR(15)					NOT NULL,
	IType					VARCHAR(15),
	CalDate				DATE,
	Status				VARCHAR(15),
	Gauge					FLOAT(6,3),
	Length				FLOAT(6,3),
	Resist				DECIMAL(24,12),	
	Protocol				VARCHAR(15),
	Capac					DECIMAL(24,12),	
	Voltage				DECIMAL(24,12),
	Amper					DECIMAL(24,12),
	Power					DECIMAL(24,12),
	TFlag					BIT(1)						NOT NULL,
	CFlag					BIT(1)						NOT NULL,
	LCFlag				BIT(1)						NOT NULL
);

CREATE TABLE STORAGE_AREA (
	StoNo					VARCHAR(3)					NOT NULL					PRIMARY KEY,
	OFlag					BIT(1)						NOT NULL,
	PFlag					BIT(1)						NOT NULL,
	BFlag					BIT(1)						NOT NULL,
	OLabel				CHAR(1),
	Plabel				CHAR(1),
	BLabel				CHAR(2)
);

CREATE TABLE DRAWER (
	DNo					VARCHAR(3)					NOT NULL					PRIMARY KEY,

	SNum					CHAR(3)						NOT NULL,
		FOREIGN KEY(SNum) REFERENCES STORAGE_AREA(StoNo)
			ON UPDATE CASCADE ON DELETE CASCADE,

	Cmpt					BIT(1)						NOT NULL
);

CREATE TABLE HOOK (
	HNo					TINYINT(2)					NOT NULL					PRIMARY KEY,
	SNum					VARCHAR(3)					NOT NULL,
		FOREIGN KEY(SNum) REFERENCES STORAGE_AREA(StoNo)
			ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE STORED_IN (
	INum					VARCHAR(9)					NOT NULL,
		FOREIGN KEY(INum) REFERENCES ITEM(INo)
			ON UPDATE CASCADE ON DELETE CASCADE,

	SNum					VARCHAR(3)					NOT NULL,
		FOREIGN KEY(SNum) REFERENCES STORAGE_AREA(StoNo)
			ON UPDATE CASCADE ON DELETE CASCADE,

	Qty					SMALlINT						DEFAULT 0
);


CREATE TABLE PURCHASE_INFO (
	INum					VARCHAR(9)					NOT NULL,

		FOREIGN KEY(INum) REFERENCES ITEM(INo)
			ON UPDATE CASCADE ON DELETE CASCADE,

	PDate					DATE							NOT NULL,
	Price					DECIMAL(10,2)				NOT NULL,
	Supplier				VARCHAR(15)					NOT NULL
);
