/* 
 * PINV database drop cleanup script
 * Created by Jarrod Nix
 *	Date: 04-09-2017
 */

/* Drop tables */
DROP TABLE IF EXISTS DRAWER;
DROP TABLE IF EXISTS HOOK;
DROP TABLE IF EXISTS STORED_IN;
DROP TABLE IF EXISTS PURCHASE_INFO;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS STORAGE_AREA;

/* Drop view */
DROP VIEW IF EXISTS ORG_STORAGE;
DROP VIEW IF EXISTS BIN_STORAGE;
DROP VIEW IF EXISTS PEG_STORAGE;
