/* 
 * PINV database drop cleanup script
 * Created by Jarrod Nix
 *	Date: 04-09-2017
 */

/* Drop Triggers */
DROP TRIGGER IF EXISTS T_Insert_Amt;

/* Drop views */
DROP VIEW IF EXISTS ORG_STORAGE;
DROP VIEW IF EXISTS BIN_STORAGE;
DROP VIEW IF EXISTS PEG_STORAGE;

/* Drop tables */
DROP TABLE IF EXISTS DRAWER;
DROP TABLE IF EXISTS HOOK;
DROP TABLE IF EXISTS STORED_IN;
DROP TABLE IF EXISTS PURCHASE_INFO;
DROP TABLE IF EXISTS STORAGE_AREA;
DROP TABLE IF EXISTS ITEM;

